services:
  rental-house-db:
    image: postgres:15
    container_name: rental-house-db
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rental-house
    ports:
      - "2345:5432"
    volumes:
      - rental-house-data:/var/lib/postgresql/data

  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      # broker administrator
      - "8161:8161"
      # internal communication pro and con
      # OpenWire
      - "61616:61616"
      # STOMP
      - "61613:61613"
    volumes:
      - activemq-data:/opt/activemq/data
    restart: unless-stopped

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554" # RTSP
      - "1935:1935" # RTMP
      - "8888:8888" # HLS
      - "8889:8889" # WebRTC
      - "8189:8189/udp" # SRT
      - "9997:9997" # API
    environment:
      - MTX_PROTOCOLS=tcp,udp
      - MTX_LOGLEVEL=info
      - MTX_WEBRTCADDITIONALHOSTS=0.0.0.0
    volumes:
      - ./mediamtx.yml:/mediamtx.yml # Optional: for custom configuration
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123  # Đã thay đổi thành mật khẩu dài hơn 8 ký tự
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3003:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    container_name: chatbot
    ports:
      - "8083:8083"
    volumes:
      - ./chatbot:/app
      - ./chatbot/chroma_lanagchain_db:/app/chroma_lanagchain_db
      - ./chatbot/output.csv:/app/output.csv
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  rental-house-data:
  activemq-data:
  minio-data:
  ollama-data:
  prometheus_data:
  grafana_data:
