export const languageTypes = {
    SET_VIETNAMESE: "SET_VIETNAMESE",
    SET_ENGLISH: "SET_ENGLISH",
    SET_FRENCH: "SET_FRENCH",
};

// Message action types
export const messageTypes = {
    SET_NEW_MESSAGE_COUNT: "SET_NEW_MESSAGE_COUNT",
    INCREMENT_MESSAGE_COUNT: "INCREMENT_MESSAGE_COUNT",
    RESET_MESSAGE_COUNT: "RESET_MESSAGE_COUNT",
};